// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"time"
)

type Dificulity struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Role struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type TriviaChoice struct {
	ID       int64  `json:"id"`
	TriviaID int64  `json:"trivia_id"`
	Choice   string `json:"choice"`
}

type TriviaDetail struct {
	UserID         int64     `json:"user_id"`
	TriviaID       int64     `json:"trivia_id"`
	TriviaStatusID int64     `json:"trivia_status_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type TriviaStatus struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Trivium struct {
	ID           int64     `json:"id"`
	Title        string    `json:"title"`
	Question     string    `json:"question"`
	Answer       string    `json:"answer"`
	DificulityID int64     `json:"dificulity_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	UserName  string    `json:"user_name"`
	RoleID    int64     `json:"role_id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserDetail struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	TriviaRound int64     `json:"trivia_round"`
	RightAnswer int64     `json:"right_answer"`
	WrongAnswer int64     `json:"wrong_answer"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
